package com.cherryleafroad.kmagick

@Suppress("unused", "EnumEntryName")
enum class ColorspaceType(val id: Int) {
    UndefinedColorspace(0),
    CMYColorspace(1),
    CMYKColorspace(2),
    GRAYColorspace(3),
    HCLColorspace(4),
    HCLpColorspace(5),
    HSBColorspace(6),
    HSIColorspace(7),
    HSLColorspace(8),
    HSVColorspace(9),
    HWBColorspace(10),
    LabColorspace(11),
    LCHColorspace(12),
    LCHabColorspace(13),
    LCHuvColorspace(14),
    LogColorspace(15),
    LMSColorspace(16),
    LuvColorspace(17),
    OHTAColorspace(18),
    Rec601YCbCrColorspace(19),
    Rec709YCbCrColorspace(20),
    RGBColorspace(21),
    scRGBColorspace(22),
    sRGBColorspace(23),
    TransparentColorspace(24),
    xyYColorspace(25),
    XYZColorspace(26),
    YCbCrColorspace(27),
    YCCColorspace(28),
    YDbDrColorspace(29),
    YIQColorspace(30),
    YPbPrColorspace(31),
    YUVColorspace(32),
    LinearGRAYColorspace(33),
    JzazbzColorspace(34),
    DisplayP3Colorspace(35),
    Adobe98Colorspace(36),
    ProPhotoColorspace(37)
}
