[package]
name = "jni-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
jni = "0.19.0"
jni-macros = { path="../jni-macros" }
thiserror = "1.0.31"
