[target.aarch64-linux-android]
ar = "aarch64-linux-android-ar.exe"
linker = "aarch64-linux-android23-clang++.cmd"

[target.armv7-linux-androideabi]
ar = "arm-linux-androideabi-ar.exe"
linker = "armv7a-linux-androideabi23-clang++.cmd"
