package com.cherryleafroad.kmagick

enum class FilterType(val id: Int) {
    UndefinedFilter(0),
    PointFilter(1),
    BoxFilter(2),
    TriangleFilter(3),
    HermiteFilter(4),
    HannFilter(5),
    HammingFilter(6),
    BlackmanFilter(7),
    GaussianFilter(8),
    QuadraticFilter(9),
    CubicFilter(10),
    CatromFilter(11),
    MitchellFilter(12),
    JincFilter(13),
    SincFilter(14),
    SincFastFilter(15),
    KaiserFilter(16),
    WelchFilter(17),
    ParzenFilter(18),
    BohmanFilter(19),
    BartlettFilter(20),
    LagrangeFilter(21),
    LanczosFilter(22),
    LanczosSharpFilter(23),
    Lanczos2Filter(24),
    Lanczos2SharpFilter(25),
    RobidouxFilter(26),
    RobidouxSharpFilter(27),
    CosineFilter(28),
    SplineFilter(29),
    LanczosRadiusFilter(30),
    CubicSplineFilter(31),
    SentinelFilter(32)
}
